In [43]:
import numpy as np
import time

In [44]:
tamanho = 10000000

In [45]:
list_py = []
lista_py = [x for x in range(tamanho)]
print(lista_py[:10])
print(lista_py[-10:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9999990, 9999991, 9999992, 9999993, 9999994, 9999995, 9999996, 9999997, 9999998, 9999999]


In [46]:
tempo_inicio = time.process_time()
lista_py_mut = [x*2 for x in lista_py]
tempo_final = time.process_time() - tempo_inicio 
print(tempo_final)

0.5625


In [47]:
numpy_array = np.array(lista_py)

print(numpy_array[:10])
print(numpy_array[-10:])


[0 1 2 3 4 5 6 7 8 9]
[9999990 9999991 9999992 9999993 9999994 9999995 9999996 9999997 9999998
 9999999]


In [48]:
tempo_inicio_np = time.process_time()
numpy_array_mut = numpy_array * 2
tempo_final_np = time.process_time() - tempo_inicio_np
print(tempo_final_np)

0.03125


In [52]:
lista = [1, 2, 3]
np_array= np.array(lista)
np_array


array([1, 2, 3])

In [63]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matriz, type( matriz))

print('-------------->')

print(np.matrix(matriz))
print(type(np.matrix(matriz)))

print('-------------->')

print(np.array(matriz))
print(type(np.array(matriz)))

print('-------------->')

[[1, 2, 3], [4, 5, 6], [7, 8, 9]] <class 'list'>
-------------->
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>
-------------->
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
-------------->


In [65]:
lista_range = list(range(11))
print(lista_range)
print(type(lista_range))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


In [70]:
array_range = np.array(range(11))
print(array_range)
print(type(array_range))

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [73]:
zero = np.zeros(5) 
print(zero, type(zero))

matriz_zeros = np.zeros((3,3))
print(matriz_zeros)

[0. 0. 0. 0. 0.] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [76]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
np.random.rand(3,4)+1

array([[1.34490373, 1.75523276, 1.88998133, 1.8828105 ],
       [1.38494657, 1.02899772, 1.73071714, 1.16106892],
       [1.78363089, 1.85693274, 1.20313183, 1.03394423]])

In [84]:
np.random.random((3,4))

array([[0.55323228, 0.44612874, 0.11538693, 0.98275117],
       [0.65422669, 0.94030528, 0.26103814, 0.24985038],
       [0.68051223, 0.35428197, 0.8991543 , 0.00708502]])

In [86]:
np.random.randn(3,4)

array([[-1.22018498,  1.16012486, -0.72694712,  1.50994587],
       [ 1.29460679,  1.0696445 ,  1.49327495,  0.80727816],
       [ 1.00823943, -0.66714197,  1.87874636, -0.73295171]])

In [87]:
np.random.seed(3)
np.random.randint(25,size=(3,4))

array([[10, 24,  3, 24],
       [ 8,  0, 21, 19],
       [10, 11,  9, 10]], dtype=int32)